function [] = writeFluidVTK(mesh,writeFile)
% file path
fid = fopen(writeFile, 'wb');

% Write VTK file header
fprintf(fid, '# vtk DataFile Version 3.0\n');
fprintf(fid, 'VTK file generated by MATLAB\n');
fprintf(fid, 'BINARY\n');
fprintf(fid, 'DATASET STRUCTURED_GRID\n');

% Write grid dimensions
fprintf(fid, 'DIMENSIONS %d %d %d\n', mesh.nx, mesh.ny, mesh.nz);

% Write point coordinates
fprintf(fid, 'POINTS %d float\n', mesh.nx * mesh.ny * mesh.nz);

% Write coordinates in binary format
fwrite(fid, [mesh.x(:), mesh.y(:), mesh.z(:)]', 'float32', 'ieee-be'); % i,j,k

% Write point data
fprintf(fid, 'POINT_DATA %d\n', mesh.nx * mesh.ny * mesh.nz);

% Write velocity components
fprintf(fid, 'VECTORS velocity float\n');
velocity = [mesh.u(:), mesh.v(:), mesh.w(:)]';
fwrite(fid, velocity(:), 'float32', 'ieee-be');

% Close the file
fprintf('Writing ready : %s\n', writeFile)
fclose all;
end
